<?php


namespace Codwelt\Blog\Http\Resources;
use Carbon\Carbon;
use Codwelt\Blog\BlogServiceProvider;
use Codwelt\Blog\Operations\Constants\Path;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;
use Vinkla\Hashids\Facades\Hashids;


/**
 * Class Post
 * @package Codwelt\Blog\Http\Resources
 * @author FuriosoJack <iam@furiosojack.com>
 */
class PostResource extends JsonResource
{

    public static function collection($resource)
    {
        return parent::collection($resource); // TODO: Change the autogenerated stub
    }

    public function toArray($request)
    {
        Carbon::setLocale('es');
        $data = [
            'id' => Hashids::encode($this->id),
            'titulo' => $this->titulo,
            'contenido' => $this->contenido,
            'resumen' => $this->resumen,
            'files' => [
                'imgThumbnail' => $this->getUrlMiniImage(),
                'imgHeader' => $this->getUrlHeaderImage()
            ],
            'fecha_publicacion' => $this->created_at->format("Y-m-d H:m:s"),
            'autor' => new CreatorResource($this->creador),
            'meta_keywords' => $this->meta_keywords,
            'url' => $this->getURL(),
            'slug' => $this->slug,
            'hashtags' => HashTagResource::collection($this->hashtags),
            'fuentes' => FuenteResource::collection($this->fuentes),
            'urlRelated' => $this->getUrlRelated(),
            'estado' => $this->state,
            "comentarios_total" => $this->comments()->count()
        ];


        return $data;
    }

   /*
   Informacion en el meta
   public function with($request)
    {
        $myWith = [
            'meta' => [
                'author' => $this->creador->getNameModel(),
                'title' => $this->titulo,
                'og:title' => $this->titulo,
                'twitter:title' => $this->titulo,
                'description' => $this->resumen,
                'og:description' => $this->resumen,
                'twitter:description' => $this->resumen,
                'og:image' => url('storage/'.$this->patch_miniatura),
                'twitter:url' => 'http://url',
                'og:url' => 'http://url',
                'keyworks' => 'tagy, tag2,tag,3',
                'robots' => 'rbosts del post',
                'canonical' => 'http://caninocal'


            ]
        ];

        return $myWith;
    }*/

}